### ISSUE TITLE
failed to apply patch 'source/target file does not exist'

### ISSUE THREAD

**Issue by derived-coder** [conan-io/python-patch-ng#15]
conan version: 1.21.1
OS: Linux Ubuntu 18.04

download the tar archive from: https://github.com/GENIVI/capicxx-core-runtime/releases/tag/3.1.12.6
Apply following patch: [0001-cmake-Modernize-exported-CMake-config-files.zip](https://github.com/conan-io/python-patch-ng/files/4471537/0001-cmake-Modernize-exported-CMake-config-files.zip)

I get following message:
```
patches/0001-cmake-Modernize-exported-CMake-config-files.patch: premature end of source file b'CMakeLists.txt' at hunk 1
patches/0001-cmake-Modernize-exported-CMake-config-files.patch: source file is different - b'CMakeLists.txt'
patches/0001-cmake-Modernize-exported-CMake-config-files.patch: source/target file does not exist:
  --- b'cmake/CommonAPIConfig.cmake.in'
  +++ b'cmake/CommonAPIConfig.cmake.in'
```

patch should be applied without any error, the PR can be merged without any problem.

**Comment by memsharded** [comment]
It worked fine here.

I downloaded the repo. Checkout tag 3.1.12.6
Then run ``python patch_ng.py 10.patch`` with the downloaded file.

It patched successfully the code.

**Comment by derived-coder** [comment]
uploaded patch, which was used

**Comment by derived-coder** [comment]
please close, I forgot to add the `basepath` to the yml file :cry:
