### ISSUE TITLE
TypeError: startswith first arg must be str or a tuple of str, not bytes

### ISSUE THREAD

**Issue by KOLANICH** [conan-io/python-patch-ng#20]
```
  File "/usr/local/lib/python3.9/dist-packages/patch_ng.py", line 454, in parse
    while not fe.is_empty and not fe.line.startswith(b"--- "):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

Probably the best solution is to just drop python 2.

**Comment by uilianries** [comment]
Python 2.x is EOL (https://www.python.org/doc/sunset-python-2/) and currently, Conan client requires Python 3.6 at least:

- https://github.com/conan-io/tribe/blob/main/design/003-codebase-python.md
- https://github.com/conan-io/conan/pull/11360

Unless it has an issue related bug with Conan client, I'm don't think it will worth.

I'll be closing issue. Please, feel free to re-open in case you think worth investing resource on it.
