### ISSUE TITLE
Broken pypy link

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [conan-io/python-patch-ng#27]
Hi,

The url `https://pypi.org/pypy/patch-ng` for the repo leads to a 404

**Comment by MatthewScholefield** [comment]
Correct link is https://pypi.org/project/patch-ng/. @uilianries Any chance you can update it?

**Comment by uilianries** [comment]
Done, the url has been updated. Thank you for reporting! 

![Screenshot 2024-05-14 at 08-50-56 conan-io_python-patch-ng Library to parse and apply unified diffs](https://github.com/conan-io/python-patch-ng/assets/4870173/dabc9ac4-17bc-4d99-8f1f-bc2cb192624d)
