### ISSUE TITLE
Project maintenance status

### ISSUE THREAD

**Issue by vonschultz** [conan-io/python-patch-ng#28]
It's been a while since the last release now, and there are some issues I'd like to see fixed (#10 comes to mind). How active is this project?

I think it would make sense to make one release a year, even if there hasn't been any functional changes to the code — that's the release frequency of Python itself, and each new release of patch-ng could update to support (and test) the latest Python version, while dropping support for the version that went end-of-life. (I do think it's time to drop Python 2 support, for example.)

If we decide on some maintenance strategy, I could potentially help out a bit myself here, sending in some pull requests for example.

**Comment by uilianries** [comment]
Closing this issue due the given response. Please, feel free to re-open it in case having more topics to discuss.
