### ISSUE TITLE
Move "custom" functionality from conan codebase

### ISSUE THREAD

**Issue by lasote** [conan-io/python-patch-ng#3]
Fix here, remove there.

**Comment by uilianries** [comment]
Verifying the code present in Conan and the code which was merged to python-patch-ng, I can say we don't need to get anything from Conan codebase to here.

To be more precise, the PR https://github.com/techtonik/python-patch/pull/41 is enough to replace our workaround which I've removed here: https://github.com/conan-io/conan/pull/5761/commits/1ac364b099dfdf30eec5553fbbdd78cc6733c48a
