### ISSUE TITLE
Please tag 1.17.2 version on git repository

### ISSUE THREAD

**Issue by winterheart** [conan-io/python-patch-ng#9]
Hello.
1.17.2 git tag is missing, can you please tag appropriate commit?

**Comment by jgsogo** [comment]
I'm sorry for the inconvenience. I've created a new release 1.17.3 (https://github.com/conan-io/python-patch-ng/releases/tag/1.17.3) with the proper tag, is it enough for your needs?

**Comment by uilianries** [comment]
Done: https://github.com/conan-io/python-patch-ng/releases/tag/1.17.2

That's is based on the real 1.17.2 version. Anyway, @jgsogo thanks for tagging the current version, it helps a lot.
